---
layout: archive
title: Zulip Chat Archive
permalink: /stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/stream/113488-general/index.html">general</a></h2>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html">"Build mathlib" fails without logs</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com/">

<head><link href="/style.css" rel="stylesheet"></head>

{% raw %}

<a name="291371791"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/%22Build%20mathlib%22%20fails%20without%20logs/near/291371791" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Markus Himmel <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html#291371791">(Jul 29 2022 at 19:42)</a>:</h4>
<p>It has happened to me multiple times that a mathlib CI run just fails at the "leanpkg build" step without any logs for that step (not even in the downloadable log archive). The most recent example is here: <a href="https://github.com/leanprover-community/mathlib/runs/7583567697?check_suite_focus=true">https://github.com/leanprover-community/mathlib/runs/7583567697?check_suite_focus=true</a></p>
<p>How do I solve this? Is this a well-known problem?</p>



<a name="291373741"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/%22Build%20mathlib%22%20fails%20without%20logs/near/291373741" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Junyan Xu <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html#291373741">(Jul 29 2022 at 20:02)</a>:</h4>
<p>Yes the problem appears often. On <a href="https://github.com/leanprover-community/mathlib/actions/runs/2762328423">this page</a> you can see the message:</p>
<blockquote>
<p>The self-hosted runner: nela lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.</p>
</blockquote>
<p>What you need to do is simply Re-run jobs -&gt; Re-run failed jobs.</p>



<a name="291374314"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/%22Build%20mathlib%22%20fails%20without%20logs/near/291374314" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Markus Himmel <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html#291374314">(Jul 29 2022 at 20:07)</a>:</h4>
<p>Awesome, thanks!</p>



<a name="291375196"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/%22Build%20mathlib%22%20fails%20without%20logs/near/291375196" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Junyan Xu <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html#291375196">(Jul 29 2022 at 20:16)</a>:</h4>
<p>I hope a re-run could be automatically triggered when Github Actions get these communication lost/out-of-resource errors. Sometimes you need to re-run twice or more to succeed in the end (some progress seems to be saved each time though). Of course you get an email when CI fails, but it wastes time to do it manually, and what if you're sleeping ...</p>



<a name="291502123"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/%22Build%20mathlib%22%20fails%20without%20logs/near/291502123" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Junyan Xu <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/.22Build.20mathlib.22.20fails.20without.20logs.html#291502123">(Jul 31 2022 at 17:30)</a>:</h4>
<p>More recently it seems (at least sometimes) the machine no longer loses communication when running out of resource; instead it reports "Process completed with exit code 137." So if you see such a message please re-run the failed job.</p>



{% endraw %}

<hr><p>Last updated: Jan 25 2023 at 00:06 UTC</p>