[
    {
        "content": "<p>There are no errors left and locally the linter did not say anything was wrong: <br>\nHowever I get the simpNF linter error again : <a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/3969088609/jobs/6803103542\">https://github.com/leanprover-community/mathlib4/actions/runs/3969088609/jobs/6803103542</a></p>",
        "id": 322546245,
        "sender_full_name": "Shreyas Srinivas",
        "timestamp": 1674229823
    },
    {
        "content": "<p>There are only two instances in this file and no theorems. So I am not sure where the issue is</p>",
        "id": 322546428,
        "sender_full_name": "Shreyas Srinivas",
        "timestamp": 1674229863
    },
    {
        "content": "<p>The CI linter gives this error message:</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"c1\">-- Mathlib.Data.Fintype.Basic</span>\n<span class=\"k\">#check</span> <span class=\"n\">Fintype.univ_ofSubsingleton.</span><span class=\"o\">{</span><span class=\"n\">u_1</span><span class=\"o\">}</span> <span class=\"c\">/-</span><span class=\"cm\"> LINTER FAILED:</span>\n<span class=\"cm\">simplify fails on left-hand side:</span>\n<span class=\"cm\">failed to synthesize</span>\n<span class=\"cm\">  Fintype Î±</span>\n<span class=\"cm\">(deterministic) timeout at 'typeclass', maximum number of heartbeats (20000) has been reached (use 'set_option synthInstance.maxHeartbeats &lt;num&gt;' to set the limit) -/</span>\n<span class=\"n\">make</span><span class=\"o\">:</span> <span class=\"bp\">***</span> <span class=\"o\">[</span><span class=\"n\">GNUmakefile</span><span class=\"o\">:</span><span class=\"mi\">16</span><span class=\"o\">:</span> <span class=\"n\">lint</span><span class=\"o\">]</span> <span class=\"n\">Error</span> <span class=\"mi\">1</span>\n</code></pre></div>",
        "id": 322547080,
        "sender_full_name": "Shreyas Srinivas",
        "timestamp": 1674230021
    },
    {
        "content": "<p>The error it's flagging is in a completely different file to the one you're PRing, right? So somehow the instance you're adding has made type class inference go bad. Try adding it in the relevant file and experimenting there, turn the instance trace on etc. There might be a simple explanation.</p>",
        "id": 322547363,
        "sender_full_name": "Kevin Buzzard",
        "timestamp": 1674230077
    },
    {
        "content": "<p>okay. I'll try that</p>",
        "id": 322548021,
        "sender_full_name": "Shreyas Srinivas",
        "timestamp": 1674230249
    },
    {
        "content": "<p>I can't get the linter to throw errors locally.</p>",
        "id": 322554449,
        "sender_full_name": "Shreyas Srinivas",
        "timestamp": 1674231921
    }
]