[
    {
        "content": "<p>Why weren't some checks successful there? <a href=\"https://github.com/leanprover-community/mathlib/issues/8956\">#8956</a></p>",
        "id": 252219239,
        "sender_full_name": "Alex Zhang",
        "timestamp": 1630959251
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"408694\">@Alex Zhang</span> I think everything is fine. Your PR was part of a batch that failed due to another PR.</p>",
        "id": 252219298,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1630959304
    },
    {
        "content": "<p>So do you mean I don't need to do anything with it?</p>",
        "id": 252219335,
        "sender_full_name": "Alex Zhang",
        "timestamp": 1630959336
    },
    {
        "content": "<p>So bors got upset, will retry your PR in another batch. (The faulty PR has been identified, and was taken off the queue.)</p>",
        "id": 252219344,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1630959343
    }
]