[
    {
        "content": "<p>It has happened to me multiple times that a mathlib CI run just fails at the \"leanpkg build\" step without any logs for that step (not even in the downloadable log archive). The most recent example is here: <a href=\"https://github.com/leanprover-community/mathlib/runs/7583567697?check_suite_focus=true\">https://github.com/leanprover-community/mathlib/runs/7583567697?check_suite_focus=true</a></p>\n<p>How do I solve this? Is this a well-known problem?</p>",
        "id": 291371791,
        "sender_full_name": "Markus Himmel",
        "timestamp": 1659123756
    },
    {
        "content": "<p>Yes the problem appears often. On <a href=\"https://github.com/leanprover-community/mathlib/actions/runs/2762328423\">this page</a> you can see the message:</p>\n<blockquote>\n<p>The self-hosted runner: nela lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.</p>\n</blockquote>\n<p>What you need to do is simply Re-run jobs -&gt; Re-run failed jobs.</p>",
        "id": 291373741,
        "sender_full_name": "Junyan Xu",
        "timestamp": 1659124928
    },
    {
        "content": "<p>Awesome, thanks!</p>",
        "id": 291374314,
        "sender_full_name": "Markus Himmel",
        "timestamp": 1659125268
    },
    {
        "content": "<p>I hope a re-run could be automatically triggered when Github Actions get these communication lost/out-of-resource errors. Sometimes you need to re-run twice or more to succeed in the end (some progress seems to be saved each time though). Of course you get an email when CI fails, but it wastes time to do it manually, and what if you're sleeping ...</p>",
        "id": 291375196,
        "sender_full_name": "Junyan Xu",
        "timestamp": 1659125775
    },
    {
        "content": "<p>More recently it seems (at least sometimes) the machine no longer loses communication when running out of resource; instead it reports \"Process completed with exit code 137.\" So if you see such a message please re-run the failed job.</p>",
        "id": 291502123,
        "sender_full_name": "Junyan Xu",
        "timestamp": 1659288629
    }
]