[
    {
        "content": "<p>Dear All,</p>\n<p>a batch of PRs are trying to get merged, but CI failed to incorporate them in mathlib.  I am the author of one of them (PR <a href=\"https://github.com/leanprover-community/mathlib/issues/6993\">#6993</a>), I see that bors says that there are merge conflicts, but does not actually say what the conflicts are (or, at least, I cannot figure it out).</p>\n<p>Is there something that I can/should do?  Will it simply fix itself by running yet another time?</p>\n<p>Thanks!</p>",
        "id": 233296707,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617704753
    },
    {
        "content": "<p>It means that your PR conflicted with another one in the batch</p>",
        "id": 233296856,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1617704825
    },
    {
        "content": "<p>If that batch succeeds, then github will show you what the conflict is once the thing it conflicts with is in master</p>",
        "id": 233296893,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1617704847
    },
    {
        "content": "<p>Ok, but it already failed a couple of times and I do not know where to look for the merge conflict...</p>",
        "id": 233297019,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617704901
    },
    {
        "content": "<p>I only see the one failure</p>",
        "id": 233297064,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1617704929
    },
    {
        "content": "<p>Your PR is still in the queue: <a href=\"https://app.bors.tech/repositories/24316\">https://app.bors.tech/repositories/24316</a></p>",
        "id": 233297106,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1617704961
    },
    {
        "content": "<p>Yes, but this one, another PR from the same batch as mine, also has a similar status:<br>\n<a href=\"https://github.com/leanprover-community/mathlib/pull/7055\">https://github.com/leanprover-community/mathlib/pull/7055</a></p>\n<p>I imagine that (some of) the others would, as well.</p>",
        "id": 233297152,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617705000
    },
    {
        "content": "<p>The PR went back into the queue already.  After after having been \"yellow\" for a while, it got the red cross and went back into the queue.</p>",
        "id": 233297281,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617705053
    },
    {
        "content": "<p>This happened a few times today.</p>",
        "id": 233297318,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617705071
    },
    {
        "content": "<p>It seems a good explanation that there is some merge conflict internal to the batch that is preventing bors to merge, but I do not know how to figure out what the conflict is.</p>",
        "id": 233297467,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617705158
    },
    {
        "content": "<p>Bors is now bisecting the commits, trying to figure out which batch of commits causes the failure</p>",
        "id": 233297493,
        "sender_full_name": "Anne Baanen",
        "timestamp": 1617705182
    },
    {
        "content": "<p>Ah, ok!  So the approach is to sit and wait and, at some point, there will be a conflict to repair, right?</p>\n<p>Thanks for the explanation!</p>",
        "id": 233297590,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1617705236
    },
    {
        "content": "<p>If the currently running batch succeeds, they will just be merged. If it fails, bors will try again with half of the commits, until it finds the PR(s) causing the failure.</p>",
        "id": 233297976,
        "sender_full_name": "Anne Baanen",
        "timestamp": 1617705464
    },
    {
        "content": "<p>(I don't see an obvious conflict from the PR descriptions at least.)</p>",
        "id": 233298079,
        "sender_full_name": "Anne Baanen",
        "timestamp": 1617705523
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib/issues/7021\">#7021</a> had a merge conflict, which I fixed.</p>",
        "id": 233341271,
        "sender_full_name": "Floris van Doorn",
        "timestamp": 1617723169
    },
    {
        "content": "<p>Thanks!</p>",
        "id": 233341737,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1617723358
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"110087\">@Scott Morrison</span>, are you really managing the tags of <a href=\"https://github.com/leanprover-community/mathlib/pull/13798\">#13798</a> live or is there some Github witchcraft going on?</p>",
        "id": 280947358,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1651533374
    },
    {
        "content": "<p>Ah!</p>",
        "id": 280947393,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1651533411
    },
    {
        "content": "<p>Because of the API rate limits, we decided to \"diversify\" the API tokens we're using to run various bots.</p>",
        "id": 280947422,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1651533426
    },
    {
        "content": "<p>For now the merge conflict bot is running off a token from my account, so it says it is me. :-)</p>",
        "id": 280947441,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1651533442
    },
    {
        "content": "<p>I will go create a new account and replace the token soon!</p>",
        "id": 280947454,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1651533452
    },
    {
        "content": "<p>(This doesn't require a new PR.)</p>",
        "id": 280947465,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1651533462
    },
    {
        "content": "<p>Ah! And people are still saying that an AI can't do theorem proving?</p>",
        "id": 280947564,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1651533536
    }
]