[
    {
        "content": "<p>I've had several mathlib CI runs fail in the last couple of days with errors in the test \"Check for modifications to ported files\". The error message is something like \"Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo\". Is this a known issue?</p>\n<p>(It seems that merging the latest upstream master immediately before pushing suppresses the error, but this is clearly not how things are supposed to work.)</p>",
        "id": 315671780,
        "sender_full_name": "David Loeffler",
        "timestamp": 1670960648
    },
    {
        "content": "<p>Probably fixed by <a href=\"https://github.com/leanprover-community/mathlib/pull/17914\">#17914</a>. Did the last failure include this fix?</p>",
        "id": 315674703,
        "sender_full_name": "Mauricio Collares",
        "timestamp": 1670961545
    },
    {
        "content": "<p>Looks like it didn't, so that's probably it then. Sorry for the noise!</p>",
        "id": 315678405,
        "sender_full_name": "David Loeffler",
        "timestamp": 1670962726
    },
    {
        "content": "<p>I was just taking a guess, since I didn't find the actual error message anywhere. It's nice to have it documented here.</p>",
        "id": 315691221,
        "sender_full_name": "Mauricio Collares",
        "timestamp": 1670967509
    },
    {
        "content": "<p>Yeah this might be the first time it's been mentioned here (it's been brought up on the discord and also in PMs to me). Thanks for flagging it David!</p>",
        "id": 315691547,
        "sender_full_name": "Kevin Buzzard",
        "timestamp": 1670967629
    },
    {
        "content": "<p>Yeah, this is my fault but can be ignored. For some reason \"ask GitHub which files changed without a full mathlib checkout\" is a hard problem, even though the GitHub UI shows it to humans...</p>",
        "id": 315720853,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670981804
    },
    {
        "content": "<p>List of runs is here: <a href=\"https://github.com/leanprover-community/mathlib/actions/workflows/add_ported_warnings.yml\">https://github.com/leanprover-community/mathlib/actions/workflows/add_ported_warnings.yml</a></p>",
        "id": 315720919,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670981857
    },
    {
        "content": "<p>Fix seems to be here: <a href=\"https://github.com/jitterbit/get-changed-files/issues/19#issuecomment-854657729\">https://github.com/jitterbit/get-changed-files/issues/19#issuecomment-854657729</a></p>",
        "id": 315721041,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670981952
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib/pull/17936\">#17936</a></p>",
        "id": 315794828,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1671017277
    },
    {
        "content": "<p>Can someone merge the above? We'll continue to get spurious errors until that's merged, which also means we won't spot edits to ported files.</p>",
        "id": 315930896,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1671058855
    }
]