[
    {
        "content": "<p>My PR <a href=\"https://github.com/leanprover-community/mathlib/pull/13307\">#13307</a> is failing the <code>continuous integration / Build mathlib (push)</code> check and I'm unable to figure out why. </p>\n<p>The first thing I tried was looking through the code in the \"Files changed\" section of the PR, which usually contains error messages when my commits fail linter checks. This didn't work though, since I guess building mathlib is much more complicated than checking style. </p>\n<p>I also tried running <code>leanproject get-cache</code> on my machine, expecting that my code would stop compiling as a result of something in the new mathlib, but everything still seems to work. </p>\n<p>I'm not sure how to find the problem - can anyone advise me? Thanks!</p>",
        "id": 281946397,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652266046
    },
    {
        "content": "<p>This means the runner (the machine running CI) disconnected from the network. I've just restarted the job.</p>",
        "id": 281946585,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1652266179
    },
    {
        "content": "<p>Oh, so the code is probably fine? Why would the runner disconnect?</p>",
        "id": 281946652,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652266204
    },
    {
        "content": "<p>Yeah it's not your fault. I'm not sure why the runner disconnected but there are several possible reasons:</p>\n<ul>\n<li>It crashed</li>\n<li>It ran out of memory</li>\n<li>It genuinely lost the internet connection</li>\n</ul>",
        "id": 281947072,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1652266533
    },
    {
        "content": "<p>Makes sense - thanks for your help:)</p>",
        "id": 281947900,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652267036
    }
]